config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get '/about' => 'pages#about'
  get '/project' => 'pages#project'

  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:message]
      ContactMailer.contact_email(name, email, body).deliver
      flash[:success] = "Message sent. Thank you for contacting me!"
      redirect_to new_contact_path
    else
      flash[:danger] = "An error occured with your message. Please try again."
      redirect_to new_contact_path
  end
end
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def projects
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :message %>
          <%= f.text_area :message, class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProfileProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name= "viewport" content="width=device-width, initial-scale=1">
  <script src="https://use.fontawesome.com/cf4096fc5c.js"></script>
</head>
<body>
  <nav class="navbar navbar">
    <div class="container">
      <div class="navbar-header">
        <a href="https://twitter.com/takezomarks" target="_blank" >
            <i class="fa fa-twitter-square fa-2x navbar-brand" id="icons"></i>
          </a>
        <a href="http://dejatrue.tumblr.com/" target="_blank" >
            <i class="fa fa-tumblr-square fa-2x navbar-brand" id="icons"></i>
          </a>
        <a href="https://www.linkedin.com/in/tkmarks" target="_blank">
            <i class="fa fa-linkedin-square fa-2x navbar-brand" id="icons"></i>
          </a>
        <a <%= link_to root_path, class:"navbar-brand" do %>
           T.K. Marks
           <% end %>
        </a>
        <button id="navbar-button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navcol-1" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li role="presentation">
            <%= link_to 'About Me', about_path, class: 'presentation' %>
          </li>
          <li role="presentation">
            <%= link_to 'Projects & Skills', project_path, class: 'presentation' %>
          </li>
          <li role="presentation">
            <li><%= link_to "Let's Talk", new_contact_path, class:'presentation' %></li>
          </li>
          <li class="active" role="presentation">
            <%= link_to 'Home', root_path, class: 'presentation' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script>
    $(document).ready(function(){
       $("div.hidden").fadeIn().removeClass("hidden");
      });
   </script>
  </head>
  <body>
    <div class="hidden">
    <div class="jumbotron" id="jumboabout">
      <h2>About Me</h2>
        <p>During my free time I enjoy outdoor activites including baseball, snowboarding, and trail running.</p>
        <p>On my hikes through urban and rural areas, I try to appreciate my surroundings, and capture these moments in my photos. You can view my photographs and online gallery by clicking <a href="http://tmarkssf.wixsite.com/dejatrue" target="_blank">here</a> and <a href="http://dejatrue.tumblr.com/" target="_blank">here</a>.</p>
      <div class="aboutbutton">
        <button class="btn btn-default" id="aboutbutton">
          <%= link_to 'Projects & Skills', project_path, class: 'btn btn-default'%>
        </button>
      </div>
    </div>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<h2> Contact </h2>

app/views/pages/home.html.erb
<!doctype html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script>
    $(document).ready(function(){
       $("div.hidden").fadeIn().removeClass("hidden");
      });
  </script>
</head>
<body>
  <div class="hidden">
    <div class="jumbotron" id="jumbohome">
      <h2 id=homeheader>Welcome</h2>
        <p id="homep">Hello! My name is T.K. Marks, and I am a freelance web developer.</p>
          <button class="btn btn-default">
             <%= link_to 'Learn More', about_path, class: 'btn btn-default'%>
          </button>
    </div>
  </div>
      <!-- class="btn btn-default" type="button" -->
  <footer>
  </footer>
</body>
</html>

app/views/pages/project.html.erb
<!doctype html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
       $("div.hidden").fadeIn().removeClass("hidden");
       $("div.hidden2").fadeIn().removeClass("hidden2");
      });
    </script>
</head>
<body>
    <div class="hidden">
      <div class="jumbotron" id="jumboprofile">
        <div class="hidden2">
        <h2>Profile & Projects</h2>
          <h4>Summary</h4>
          <p id="paraprofile">Self taught Web Developer, experienced analyst, and account manager. Proven track record of meeting deadlines, creative problem solving, and achieving client desired results. Currently exploring opportunities in Product Management and Ownership,  as well as Web Developer roles. Available for hire as a freelance web developer and designer.</p>
        <h4>Highlights</h4>
        <ul>
          <li>Working knowledge of Ruby on Rails, jQuery, CSS, HMTL, and SQL</li>
          <li>Advanced Excel and VBA skills</li>
          <li>Google Adwords Certified</li>
          <li>Bing Ads Certified</li>
          <li>Google Analytics Certified</li>
          <li>Paid Search & Digital Marketing experience</li>
        </ul>
        <h4>Education & Training</h4>
        <p id="paraprofile">San Francisco State University</p>
        <ul>
          <li>Bachelor of Arts Biology</li>
        </ul>
        <p id="paraprofile">Coder Manual: Interactive Coding Boot Camp</p>
        <div class="aboutbutton">
        <button class="btn btn-default" id="aboutbutton">
          <%= link_to "Let's Talk", new_contact_path, class: 'btn btn-default'%>
        </button>
        </div>
      </div>
    </div>
  </div>
</body>
</html>